apply plugin: 'maven-publish'

// Dummy task to trick JitPack into thinking it compiled successfully
task assemble {}

publishing {
    publications {
        Release(MavenPublication) {
            groupId = 'com.github.skynetbee'
            artifactId = 'NeuralEngineUltra'
            version = '1.0.2'
            artifact("production-release-v1.aar")
        }
    }
}
